steps:
  # 1. Build the application container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA', '-f', 'Dockerfile', '.']
    id: 'Build'

  # 2. Push the application container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA']
    id: 'Push'

  # 3. Deploy the service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,PUBSUB_SUBSCRIPTION_ID=${_SUBSCRIPTION_ID},ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}'
      # --- General deployment settings ---
      - '--region=${_REGION}'
      - '--platform=managed'
      # Allow unauthenticated access for now. For production, you would likely
      # secure this and use an authenticated frontend or API Gateway.
      - '--allow-unauthenticated'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/${_SERVICE_NAME}:$COMMIT_SHA'

substitutions:
  _SERVICE_NAME: 'v3-notifications-service'
  _REGION: 'us-central1' # <-- IMPORTANT: Change to your preferred GCP region
  _SUBSCRIPTION_ID: 'notifications-topic-sub'
  # Comma-separated list of allowed frontend origins.
  _ALLOWED_ORIGINS: 'http://localhost:5173,https://dxmultiomics.com'